version: '3.8'
services:
  app:
    build: .
    ports:
      - "3000:3000"
    depends_on:
      - mysql
    volumes:
      - ./src:/usr/src/app/src
      - ./package.json:/usr/src/app/package.json

  mysql:
    image: mysql:8.0
    environment:
     - MYSQL_ROOT_PASSWORD=rootpassword
     - MYSQL_DATABASE=money_transfer_app
    ports:
      - "3306:3306"
    volumes:
      - mysql-data:/var/lib/mysql

volumes:
  mysql-data: