version: '3.8'
services:
  mysql:
    image: mysql:8.0
    environment:
     - MYSQL_DATABASE=db
     - MYSQL_USER=user
     - MYSQL_PASSWORD=password
     - MYSQL_ROOT_PASSWORD=password
    ports:
      - "3306:3306"
    expose:
      - '3306' 
    volumes:
      - mysql-data:/var/lib/mysql

volumes:
  mysql-data: